server.port: 8010
app.name: Twitter Bot Detector
spark.cores: local[*]

twitter:
  CONSUMER_KEY: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  CONSUMER_SECRET: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  TOKEN: XXXXXXXX-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  TOKEN_SECRET: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

request_max: 200

elasticsearch:
  nodes: 192.168.0.44
  port: 9200
